# Generated by Django 4.2.18 on 2025-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_br_cataleg_ptr_alter_categoria_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
