# Generated by Django 4.2.18 on 2025-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_exemplar_exclos_prestec'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestec',
            name='retornat',
            field=models.BooleanField(default=False),
        ),
    ]
