# Generated by Django 4.2.18 on 2025-04-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_prestec_retornat'),
        ('biblioteca', '0010_rename_cicle_grup_rename_cicle_usuari_grup'),
    ]

    operations = [
    ]
