# Generated by Django 4.2.18 on 2025-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_merge_20250430_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='codi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
