# Generated by Django 4.2.18 on 2025-05-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_merge_20250430_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
