# Generated by Django 4.2.18 on 2025-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_merge_20250430_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestec',
            name='data_retornat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
