# Generated by Django 4.2.18 on 2025-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_prestec_data_retornat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='biblioteca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exemplar',
            name='en_prestec',
            field=models.BooleanField(default=False),
        ),
    ]