# Generated by Django 4.2.18 on 2025-05-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_exemplar_codi'),
        ('biblioteca', '0012_prestec_data_retornat'),
    ]

    operations = [
    ]