# Generated by Django 4.2.18 on 2025-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_exemplar_codi'),
        ('biblioteca', '0013_exemplar_biblioteca_exemplar_en_prestec'),
    ]

    operations = [
    ]
