# Generated by Django 4.2.18 on 2025-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_merge_0012_exemplar_codi_0012_prestec_data_retornat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='en_prestec',
            field=models.BooleanField(default=False),
        ),
    ]
