# Generated by Django 4.2.18 on 2025-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_merge_20250508_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='biblioteca',
        ),
    ]
