# Generated by Django 4.2.18 on 2025-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_exemplar_en_prestec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='registre',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
