# Generated by Django 4.2.18 on 2025-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_alter_exemplar_registre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='registre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
