# Generated by Django 4.2.18 on 2025-05-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_alter_exemplar_registre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='codi',
        ),
    ]
