# Generated by Django 4.2.18 on 2025-05-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_alter_usuari_auth_token'),
        ('biblioteca', '0015_remove_exemplar_biblioteca'),
        ('biblioteca', '0017_remove_exemplar_codi'),
    ]

    operations = [
    ]
